### ISSUE TITLE
Bug: Table D- External Engagement shows incorrect numbers

### ISSUE THREAD

**Issue by khuffman** [EPSCoR/ERCore#26]
Sally discovered a bug:  under Admin Views -> NSF Table D-External Engagements both the html page and the TableD xls file are filled with incorrect numbers. The numbers shown are for all  external engagements entered into the site, and not for the reporting year range selected, so it completely ignores the "reporting year" date range.

I just tested this on NM dev server and I see the same problem there. Here is how to reproduce this:
Select reporting year Jun 1, 2014 - May 31, 2015. The go to this:
http://dev-ercore.nmepscor.net/admin/epscor/views/external-engagement
you will get a html page, in the first table labelled "Total"
- count the number of rows: it shows 7 external engagements.
- and if you sum up the numbers for last column labeled  'tot' you will get 17. 

But there should only be 5 external engagements rows shown, since 2 (rows with nid 24 and 26)  are events, dated Oct 1 and Oct 2,  2013 and should not be shown.
Now on this same page, if you click "Download this page" link you will get a TableD xls file that in row "Project Total", the last column Total shows 17, this is incorrect, because this includes the 3+3 people from the two 2013 events. The correct number should be 11 (so 17-3-3=11)

I compared these numbers with the ones generated on the Accomplishment Table, and Accomplishment table shows the correct number of External Engagements for each reporting year. So the problem seems to be only with the Admin View-Table D.
I will look at the code tomorrow, if I figure out how to fix it I will update this issue tracker. Hope someone else can verify this bug so we know that is is for sure a bug.

**Comment by aturling** [comment]
I just checked the code for pages/external-engagement.inc and I don't see anything in the code that filters out engagements for the current reporting period. The data() function seems to just query the database for all nodes of type external engagement. I don't see a date range filter in pages/collaborations.inc (Table C) either. But in page/outputs.inc it's very clear how the data is separated into queries for the entire grant range vs. the current reporting period.

Since external engagements are attached to events, which can have a date range, it seems like we would want to model the code for tables C and D after the table E code, moving the applyDateRange() function from pages/outputs.inc to er_page.inc so that it can be used in multiple pages/*.inc files.

**Comment by cjallen-epscor** [comment]
@khuffman  - I just verified the numbers and issue you discovered.
I have been saying for awhile that those "admin views" are quick and dirty and only use them as reference.  But great catch - this definitely is not breaking up by date ranges.

@aturling - I agree - we should move the applyDateRange() function into er_page.inc

**Comment by iserna** [comment]
The Admin Views have been problematic in the past and as @cjallen-epscor mentioned we only use them and reference.  Here in NM we have created several alternative views that are more accurate by award year.  

@aturling can you share your idea with us by cutting a new branch with your update?

**Comment by aturling** [comment]
Which views do you use to auto-populate the NSF tables? I thought that was the primary purpose of these admin views.

I can look into editing the code for tables C and D and submit the changes to a branch.

**Comment by iserna** [comment]
@aturling the view at /reporting/external-engagement is populating D and /reporting/collaborations populates C.  Thanks.

**Comment by aturling** [comment]
Are the /reporting/external-engagement and /reporting/collaboration views different from the admin views? On my install, clicking on Admin Views -> Table C redirects to /reporting/collaborations and Admin Views -> Table D redirects to /reporting/external-engagement, and these are populated by the /pages/*.inc files.

**Comment by iserna** [comment]
You are correct /reporting/external-engagement and /reporting/collaboration are the EPSCoR Admin Views.   It can get confusing with the EPSCoR Content views, which are different from the Admin Views.

**Comment by aturling** [comment]
I just added my changes to er_page.inc, pages/collaborations.inc, pages/external-engagement.inc, and pages/outputs.inc to the 3.1-dev-teamview branch.

I did some light testing and it seemed to work (it excluded the test collaborations and external engagements that fell outside of the reporting range), but I have a few questions on how things should be counted (on the admin side, not what the current code does).

For example, suppose the reporting range is Jan 1 2015 to Dec 31 2015:
- If a collaboration begins in Nov 2015 and concludes in Feb 2016, is it counted in the current reporting year or the next one or both?
- Suppose there's an event open to the public that consists of three workshops occurring in Dec 2015, Jan 2016, and Feb 2016, and this was entered into the system by creating a single workshop event, assigning Dec 2015 as the start date, and clicking the "repeat" button to fill in the other two dates. Then one set of external engagement data is attached to this event. Should these external engagements be counted in both reporting years?

The applyDateRange function would count the above cases in both reporting years because it just checks for overlapping date ranges - just checking if that's the right thing to do.

**Comment by iserna** [comment]
I will confirm with Mary Jo on the reporting questions and get back to you as soon as possible.  Thanks!  Also, would it be better if you created a new branch for this specific issue?

**Comment by khuffman** [comment]
My guesses are:
first question: yes, the collaboration should be counted for both 
current and next reporting year.

second question: yes, but only if the external engagement xls data gets 
re-uploaded(with the new numbers) after each of these public events.
If only one single external engagement xls data is uploaded at the first 
public event (Dec 2015) then no, that shouldn't be counted for both 
reporting years.

I asked our PA to confirm my answers, here is what she wrote:
1.  You are correct-it should counted as a collaboration in both 
reporting years.
2. Collaborations and external engagements are sometimes relational but 
not always.  In the example given, you are correct that each event will 
need a unique external engagement sheet upload.  The correct result will 
be one collaboration that counts in two reporting years, one calendar 
event/external engagement that support the work described in the 
collaboration in 2015 and two calendar events/external engagement in 
support of that collaboration in 2016.

The carryover of the collaboration in the reporting turned out to be a 
problem for me in the reporting.  That's why I asked that the end date 
be mandatory.

Hope this helps!

**Comment by aturling** [comment]
Ok I'm still trying to understand this - so does that mean that if someone enters a calendar event with "will the public attend this event?" = "yes" checked, they should never click the "repeat" button on the event, but rather enter in each event separately with each event's attendance data? So instead of one "Workshop" event that repeats 3 times, they should enter "Workshop 1", "Workshop 2", and "Workshop 3" as separate events and upload attendance data for each?

Similarly, if a collaboration overlaps two reporting periods, should the collaboration be split into two, with different descriptions for each? For example, instead of entering in one collaboration of Teams A and B that goes from Nov 2015 to Mar 2016, should they enter one collaboration from Nov 2015-Dec 2015 with a description of the work done in that month, then another collaboration from Jan 2016 - Mar 2016 with the follow-up work done in those two months?

On the coding side, if the events and collaborations are split like this, then the applyDateRange function will work. I'm wondering if additional changes could be made on the coding side to help people enter the data correctly - for example if they shouldn't check the "repeat" box for events where attendance data needs to be uploaded, maybe an additional bit of code should be added to the form validate function to check for this and throw an error explaining how the event should be split into multiple events. Similarly the code could check for collaborations overlapping reporting periods.

**Comment by khuffman** [comment]
@aturling, regarding the workshop/event: we think one could have a 
public event? = "yes" and have "repeat" button, as long as after each 
repeating workshop one remembers to upload a updated attendance data xls 
file that reflects the total number of the attendance for e.g workshop1+ 
workshop2. But I agree with you, it is easier just to create e.g. 3 
separate events and upload attendance data for each. So maybe it is 
right to not make it possible for a user to click the "repeat if the 
event is a public event? I leave it up to the Admins to decide this.

Regarding the collaboration overlapping two reporting periods: I asked 
our PA, if a collaboration should be split like the example you gave, 
she says:

"A collaboration should not be split that way.  A collaboration is in 
support of goals and objectives.  It may change slightly over time but 
not dramatically. Different descriptions=two distinct collaborations."

**Comment by aturling** [comment]
Ok thanks! Maybe the first issue can be brought up at a future admin meeting to see what everyone thinks (it might be one of those issues that each jurisdiction handles differently).
Also that makes things a lot easier if we don't have to worry about splitting up collaborations. In that case the applyDateRange function as it was written in pages/outputs.inc should work to restrict the info in tables C and D to the current reporting period.

**Comment by iserna** [comment]
@aturling Regarding workshop/events: NM thinks we should not have the repeat for Events, each event/external engagement should be entered in as it's own entry and it should have a default end date.  These are usually one day events.  Not sure if this is jurisdiction specific?  Also, fyi, in NM  most of our users do not use the excel upload.  Many enter the numbers into the "I want to enter the attendee figures manually" section.  Our users found the excel spreadsheet confusing and time consuming.

Regarding the collaborations overlapping reporting periods:  Same as RI's PA, collaborations should not be split up, they can and will be ongoing.  Though, it is up to the user or person who created it to update the collaboration with an end date.

If any of this is too confusing or overwhelming we could have a quick call if needed.  Just let me know.

Thanks!

**Comment by aturling** [comment]
@iserna I created the new branch 3.1.1-tablesfix which branched off from 3.1.1.

**Comment by iserna** [comment]
@aturling we just tested this and it works!  The issue we find here in NM is getting participants to update Collaboration end dates.

**Comment by iserna** [comment]
This issues has been resolved and committed here, https://github.com/EPSCoR/ERCore-3.1/commit/322a49d191cccc67f1fd0bde5f421bb00378e518
